force-app/main/default/objects/PICKLIST__c/PICKLIST__c.object-meta.xml
<CustomObject>
    <label>PICKLIST</label>
    <nameField>
        <displayFormat>P-{00}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PICKLISTS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PICKLIST__c/fields/CHECK__c.field-meta.xml
<CustomField>
    <fullName>CHECK__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CHECK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PICKLIST__c/fields/COMMENTS__c.field-meta.xml
<CustomField>
    <fullName>COMMENTS__c</fullName>
    <label>COMMENTS</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PICKLIST__c/fields/COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY__c</fullName>
    <label>COUNTRY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>NEWZEALAND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PICKLIST__c/fields/DESCRIPTION__c.field-meta.xml
<CustomField>
    <fullName>DESCRIPTION__c</fullName>
    <label>DESCRIPTION</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PICKLIST__c/fields/STATES__c.field-meta.xml
<CustomField>
    <fullName>STATES__c</fullName>
    <label>STATE</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>COUNTRY__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ANDHRA PRADES</fullName>
            </value>
            <value>
                <fullName>TELANGANA</fullName>
            </value>
            <value>
                <fullName>KARNATAKA</fullName>
            </value>
            <value>
                <fullName>TEXAS</fullName>
            </value>
            <value>
                <fullName>CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>NEW YORK</fullName>
            </value>
            <value>
                <fullName>SYDNEY</fullName>
            </value>
            <value>
                <fullName>PERTH</fullName>
            </value>
            <value>
                <fullName>BRISBANE</fullName>
            </value>
            <value>
                <fullName>AUCKLAND</fullName>
            </value>
            <value>
                <fullName>WILLINGTON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/myclass.cls
public class myclass {
  
    public PageReference Save() {
    
       IF(PC.CHECK__C == true){
       
           PC.DESCRIPTION__c = PC.COUNTRY__C +' ' + PC.STATES__C + '  ' + PC.COMMENTS__c;
       
       }
       ELSE{
           PC.DESCRIPTION__c = PC.COMMENTS__c;
       
       }
    
    
        UPSERT PC;
       // Pagereference pg = new pagereference('https://c.ap2.visual.force.com/apex/PV1');
        return null;

        
    }

    public PICKLIST__c pc {set; get;}
    public myclass(){
    pc= new PICKLIST__c();
    }
}